apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: counter-pipeline
spec:
  tasks:
    - name: lint
      taskRef:
        name: lint-task

    - name: test
      runAfter: ["lint"]
      taskRef:
        name: test-task

    - name: cleanup
      runAfter: ["test"]
      taskRef:
        name: cleanup-task
